---
build:
  nodes:
    analysis:
      environment:
        php:
          version: 8.1
      tests:
        override:
          - php-scrutinizer-run
  tests:
    override:
      -
        command: 'vendor/bin/phpspec run -n -fpretty'
        coverage:
          file: 'coverage.xml'
          format: 'clover'
