inherit: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpspec run -n -fpretty'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
