---
services:

  Knp\DictionaryBundle\ValueTransformer\Constant:
    public: false

  Knp\DictionaryBundle\ValueTransformer\Aggregate:
    public: false
    calls:
      - [addTransformer, ['@Knp\DictionaryBundle\ValueTransformer\Constant']]

  Knp\DictionaryBundle\ValueTransformer:
    public: false
    alias: Knp\DictionaryBundle\ValueTransformer\Aggregate
