---
services:

  knp_dictionary.dictionary.value_transformer.constant_transformer:
    public: false
    class: Knp\DictionaryBundle\Dictionary\ValueTransformer\ConstantTransformer

  knp_dictionary.dictionary.value_transformer.transformer_aggregate:
    public: false
    class: Knp\DictionaryBundle\Dictionary\ValueTransformer\TransformerAggregate
    calls:
      - [addTransformer, ['@knp_dictionary.dictionary.value_transformer.constant_transformer']]
