---
services:

  Knp\DictionaryBundle\Validator\Constraints\DictionaryValidator:
    public: false
    arguments:
      - '@Knp\DictionaryBundle\Dictionary\DictionaryRegistry'
    tags:
      - validator.constraint_validator
