---
services:

  knp_dictionary.dictionary.factory.factory_aggregate:
    public: true
    alias: Knp\DictionaryBundle\Dictionary\Factory\FactoryAggregate

  knp_dictionary.dictionary.factory.extended_factory:
    public: false
    alias: Knp\DictionaryBundle\Dictionary\Factory\Extended

  knp_dictionary.dictionary.factory.value:
    public: false
    alias: Knp\DictionaryBundle\Dictionary\Factory\Value

  knp_dictionary.dictionary.factory.key_value:
    public: false
    alias: Knp\DictionaryBundle\Dictionary\Factory\KeyValue

  knp_dictionary.dictionary.factory.value_as_key:
    public: false
    alias: Knp\DictionaryBundle\Dictionary\Factory\ValueAsKey

  knp_dictionary.dictionary.factory.callable_factory:
    public: false
    alias: Knp\DictionaryBundle\Dictionary\Factory\CallableFactory

  knp_dictionary.dictionary.factory.combined_factory:
    public: false
    alias: Knp\DictionaryBundle\Dictionary\Factory\Combined

  Knp\DictionaryBundle\Dictionary\Factory\FactoryAggregate:
    public: false
    arguments:
      - '@Knp\DictionaryBundle\Dictionary\Factory\Aggregate'
