---
services:

  knp_dictionary.twig.dictionary_extension:
    public: false
    alias: Knp\DictionaryBundle\Twig\DictionaryExtension

  Knp\DictionaryBundle\Twig\DictionaryExtension:
    public: false
    arguments:
      - '@Knp\DictionaryBundle\Dictionary\DictionaryRegistry'
