---
version: 1

update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
    allowed_updates:
      - match:
          dependency_type: "development"
    commit_message:
      prefix: 'chore'
      prefix_development: 'chore'
      include_scope: true
